service: serverless-short-linker-api

frameworkVersion: "3"

plugins:
  - serverless-esbuild

package:
  individually: true

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1

  httpApi:
    authorizers:
      customAuthorizer:
        type: request
        functionName: authorizer

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:GetItem"
            - "dynamodb:Scan"
            - "dynamodb:Query"
          Resource:
            - Fn::GetAtt:
                - ShortLinkerTable
                - Arn
        - Effect: "Allow"
          Action:
            - "secretsmanager:GetSecretValue"
            - "secretsmanager:CreateSecret"
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "events:PutEvents"
          Resource: "*"
  environment:
    TABLE_NAME: { Ref: ShortLinkerTable }

functions:
  createLink:
    handler: src/handlers/createLink.main
    events:
      - httpApi:
          path: /link
          method: post
          authorizer:
            name: customAuthorizer
  listLinks:
    handler: src/handlers/listLinks.main
    events:
      - httpApi:
          path: /links
          method: get
          authorizer:
            name: customAuthorizer
  deactivateLink:
    handler: src/handlers/deactivateLink.main
    events:
      - httpApi:
          path: /link/deactivate
          method: post
          authorizer:
            name: customAuthorizer
  redirectLink:
    handler: src/handlers/redirectLink.main
    events:
      - httpApi:
          path: /{shortAlias}
          method: get
  signUp:
    handler: src/handlers/signUp.main
    events:
      - httpApi:
          path: /auth/signup
          method: post
  signIn:
    handler: src/handlers/signIn.main
    events:
      - httpApi:
          path: /auth/signin
          method: post

  authorizer:
    handler: src/auth/authorizer.main

  deactivator:
    handler: src/handlers/deactivator.main
    events:
      - eventBridge:
          enabled: true
          schedule: rate(60 minutes)

resources:
  Resources:
    ShortLinkerTable:
      Type: "AWS::DynamoDB::GlobalTable"
      Properties:
        TableName: ShortLinkerTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        Replicas:
          - Region: eu-central-1
          - Region: us-east-1
          - Region: us-west-1
          - Region: ap-south-1
          - Region: eu-west-1
          - Region: eu-north-1
